num_features:
  - age
  - bmi
  - children
cat_features:
  - sex
  - smoker
  - region
target: charges
test_size: 0.2
random_state: 42

cv: 5
cv_scoring: neg_mean_squared_error

linear_regression: LinearRegression
linreg_param_grid:
  fit_intercept: 
  - True
  - False

ridge_regression: Ridge
ridge_regression_param_grid:
  alpha: 
    - 0.01
    - 0.1
    - 1.0
    - 10.0
  fit_intercept:
    - True
    - False
  solver:
    - auto
    - svd
    - cholesky
    - lsqr
    - sparse_cg
    - sag
    - saga

rf_regressor: RandomForestRegressor
rf_regressor_param_grid:
  n_estimators: 
    - 50
    - 100
    - 200
    - 300
    - 500
  max_depth:
    - 3 
    - 5
    - 8
    - 10
    - 20
  min_samples_split: 
    - 2
    - 5
  min_samples_leaf: 
    - 1
    - 2
  # - max_features: 
  #   - None
  bootstrap: 
    - True
    - False